# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jinjerkeihi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jinjerkeihi
  pod 'Fabric'
  pod 'Crashlytics'

  target 'jinjerkeihi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'jinjerkeihi-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jinjerkeihi-tvOS

end
